/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:a45b9d88-ffa0-4dde-9184-ef9e2265dbe9",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_7aFhOqzMq",
    "aws_user_pools_web_client_id": "97vfqniu2lldcujtj1dagn0q7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sortdatabucket224455-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
